# Generated by Django 2.2.4 on 2019-10-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191028_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='approved_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
    ]
