# Generated by Django 2.2.4 on 2019-11-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191112_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislikes',
            new_name='negative_votes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='positive_votes',
        ),
        migrations.AddField(
            model_name='post',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
