# Generated by Django 3.0.8 on 2020-07-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
